# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "opendatahub-geo-api"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-geo-api"

[[annotations]]
path = [".githooks/**", ".github/**", ".husky/**", "infrastructure/**", ".gitignore", ".gitattributes", "VectorTilesApi/.env.example", "VectorTilesApi/VectorTilesApi.csproj", "opendatahub-geo-api.sln","VectorTilesApi/appsettings.json","VectorTilesApi/appsettings.Development.json", "VectorTilesApi/Properties/launchSettings.json", "VectorTilesApi/.env"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"